version: 2.1
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     - I-Have-Code:
         requires:
           - Hello-World
     - Run-With-Node:
         requires:
           - Hello-World
     - Hold-For-Approval:
         type: approval
         requires:
           - Run-With-Node
           - I-Have-Code
     - Now-Complete:
         requires:
           - Hold-For-Approval
# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.12.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-8.12.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-8.4.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=9.11.2'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-9.11.2'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.10.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-10.10.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=12.18.3'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-12.18.3'
  - '--tag=gcr.io/$PROJECT_ID/yarn:lts'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/yarn'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=14.10.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn:node-14.10.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn:latest'
  - '--tag=gcr.io/$PROJECT_ID/yarn:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/yarn:node-8.12.0'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn:node-8.4.0'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn:node-9.11.2'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn:node-10.10.0'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn:node-12.18.3'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn:node-14.10.0'
  args: ['--version']
